[DASA-2822][DSVA-294] - Fix training loop - remove fast cocoeval api, add mlflow to training and evaluation loop and update requirements.
360iQ/YOLOX pull request #3
Opened 2023-08-30 13:35 UTC by beazy96

Mlflow experiment: http://192.168.189.67:8888/#/experiments/388

2023-08-31 10:24 UTC, pkolebski requested changes

2023-08-31 10:24 UTC, pkolebski commented on yolox/evaluators/coco_evaluator.py
> +            return 0, 0, None, {0: 0}, {0: 0}
return empty dicts

2023-08-31 10:24 UTC, pkolebski commented on yolox/evaluators/coco_evaluator.py
> +            logger.warning("Use standard COCOeval.")
remove log as this is only available option now.

2023-08-31 10:24 UTC, pkolebski commented on yolox/layers/__init__.py
> +"""Module deleted."""
just delete this file if it is the last one in directory. If not, change docstring to something more informative.

2023-08-31 10:24 UTC, pkolebski commented on yolox/layers/fast_coco_eval_api.py
> +"""Module deleted."""
delete this file.

2023-08-31 11:25 UTC, dpolak-dtiq requested changes

2023-08-31 11:25 UTC, dpolak-dtiq commented on yolox/layers/jit_ops.py
> +        except (Exception, ModuleNotFoundError):  # op not compiled, jit load
remove this inline comment

2023-09-01 10:23 UTC, pkolebski approved these changes

2023-09-06 13:21 UTC, dpolak-dtiq approved these changes

2023-09-06 13:22 UTC, merged