[DASA-2914][DASA-2915] - Allow run YoloX trainings as method and allow YoloX trainings use our dataset images' location
360iQ/YOLOX pull request #4
Opened 2023-12-20 11:43 UTC by beazy96

2023-12-20 11:59 UTC, pkolebski requested changes

2023-12-20 11:59 UTC, pkolebski commented on yolox/data/datasets/coco.py
> +    def get_image_paths(self):
add log about loading images paths

2023-12-22 10:05 UTC, wsliwinska commented on yolox/data/datasets/coco.py
> +        print(f"Found {len(image_paths)} images in {self.data_dir}")
print -> log.info

2024-01-10 16:28 UTC, wsliwinska approved these changes

2024-01-12 10:27 UTC, pkolebski approved these changes

2024-01-12 10:35 UTC, wsliwinska approved these changes

2024-01-12 10:37 UTC, wsliwinska approved these changes

2024-01-12 10:38 UTC, wsliwinska approved these changes

2024-01-12 10:40 UTC, merged