[DSVA-2528] Implement othe IoU losses
360iQ/YOLOX pull request #7
Opened 2024-01-25 07:51 UTC by pkolebski

2024-01-25 08:21 UTC, pkolebski commented
In `N:\ComputerVision\projects\datasets_cleaning\datasets\05_cumultative_training\models\test_subdataset5_ciou/train_log.txt` you can find traceback

2024-02-05 09:57 UTC, Pawel842 requested changes

2024-02-05 09:57 UTC, Pawel842 commented on yolox/models/losses.py
> +    return d, c
imo to make sure it's proper calculation that methods needs unit tests.

2024-02-06 07:59 UTC, AnhelinaRusak reviewed
Just add tests, as Paweł mentioned

2024-02-13 10:31 UTC, pkolebski commented on yolox/data/datasets/coco.py
>          assert image is not None, f"file named {image_file_path} not found"
I had often problems with loading images - probably issues with VPN/network drive connection. With this "fix" I could run full training without error.

2024-02-14 08:41 UTC, Pawel842 approved these changes

2024-02-14 08:49 UTC, AnhelinaRusak approved these changes

2024-02-14 08:49 UTC, merged