[DASA-3054] - inference in batch
360iQ/YOLOX pull request #9
Opened 2024-02-26 13:35 UTC by beazy96

2024-02-29 08:16 UTC, pkolebski requested changes

2024-02-29 08:16 UTC, pkolebski commented on tools/demo.py
> +        Inference with batch images.
Add info that this method is is equivalent to `inference` but for batches.

2024-02-29 08:16 UTC, pkolebski commented on tools/demo.py
> +        processed_images = []
add typing

2024-02-29 16:11 UTC, pkolebski approved these changes

2024-03-01 12:16 UTC, AnhelinaRusak approved these changes

2024-03-01 12:16 UTC, merged